version: "3.8"
services:
  mysql-primary.mysql.svc.cluster.local:   # I made such a service name for mysql container because in that case I do not need to change application.properties file.
    image: mysql:8.0.0
    environment:
      MYSQL_ROOT_PASSWORD: Dexter@123
      MYSQL_DATABASE: bankappdb
    ports:
    - "3306:3306"
    volumes:
    - db_data:/var/lib/mysql
  app:
    build:
      context: ./
      dockerfile: Dockerfile-Project-1
    depends_on:
      - mysql-primary.mysql.svc.cluster.local
    environment:
      JDBC_URL: jdbc:mysql://mysql-primary.mysql.svc.cluster.local:3306/bankappdb?useSSL=false&serverTimezone=UTC
      JDBC_USER: root
      JDBC_PASS: Dexter@123
    ports:
    - "8080:8080"
volumes:
  db_data:
